name: wendymatthews
favicon: null
layout_spectrum: 0.6969732358120382
typography_spectrum: 0.48762467433698475
title: Inbound Marketing Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#fe7e00'
    - '#bebebe'
    - '#3b3b3b'
  brandStrength: 0.1875
  lightness: 0.5962522744666785
  saturation: 0.8365487107075751
  rhythmicContrast: 0.8883621813729405
purpose: []
