name: wendymatthews
favicon: null
layout_spectrum: 0.6969732358120382
typography_spectrum: 0.48762467433698475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.969673631945625
  lightness: 0.5962522744666785
  saturation: 0.8365487107075751
  rhythmicContrast: 0.8883621813729405
purpose: []
